# Development overrides for docker-compose.yml
# This file is automatically loaded by docker-compose in development
# Use: docker-compose up -d (for local development)

version: '3.8'

services:
  postgres:
    environment:
      - POSTGRES_PASSWORD=trading_pass  # Plain text for development
    ports:
      - "5432:5432"  # Expose port for local access
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - ./scripts/seed-dev-data.sql:/docker-entrypoint-initdb.d/99-seed.sql

  redis:
    ports:
      - "6379:6379"  # Expose port for local access
    command: redis-server --appendonly yes --protected-mode no

  # Development API services (when ready)
  # market-data-api:
  #   build: 
  #     context: ./services/market-data
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ./services/market-data:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #     - DATABASE_URL=postgresql://trading_user:trading_pass@postgres:5432/trading_db
  #     - REDIS_URL=redis://redis:6379
  #     - HOT_RELOAD=true
  #   ports:
  #     - "8002:8002"
  #   command: npm run dev

  # analysis-api:
  #   build:
  #     context: ./services/analysis
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ./services/analysis:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #     - DATABASE_URL=postgresql://trading_user:trading_pass@postgres:5432/trading_db
  #     - REDIS_URL=redis://redis:6379
  #     - HOT_RELOAD=true
  #   ports:
  #     - "8003:8003"
  #   command: npm run dev

  # Development tools
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_DESIGN=pepa-linha

  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379