apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-providerb
  namespace: default
spec:
  scaleTargetRef:
    kind: Deployment
    name: market-data-worker-providerb
  minReplicaCount: 1
  maxReplicaCount: 10
  cooldownPeriod: 120
  pollingInterval: 15
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://kube-prometheus-stack-prometheus.monitoring.svc:9090
        query: sum(rate(worker_batch_fetch_total{provider="providerB"}[1m]))
        threshold: "3"
        activationThreshold: "0.25"
