apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-config
  namespace: monitoring
data:
  blackbox.yaml: |
    modules:
      http_2xx:
        prober: http
        timeout: 10s
        http:
          method: GET
          valid_http_versions: ["HTTP/1.1", "HTTP/2"]
          preferred_ip_protocol: "ip4"
